### ISSUE TITLE
Short wiki page on other intelij plugins

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/IntelliJ-Spartanizer#15] opened 2016-11-27 14:31 UTC
Here you will write a wiki page in this project to describe the essence of difficulties and advantages and insights gained by examining a specific plugin, maybe more than one.

**Comment by amirsagiv83** [comment] 2016-11-28 20:12
@orenafek 
I'm not closing this Issue yet. After you and Michal finish your work on the first plugin, decide whether or not this issue is still relevant. if not, close it!

**Comment by michalcohen** [comment] 2016-12-06 20:39
As the team showed a progress in several directions (extending the POC, importing leonidas using only PSI or ASTNode) I see no extra benefit in analysing other plugins.

**Comment by yossigil** [comment] 2016-12-07 06:47
I think there is.... The reason is that with the absence of this background information, we do not have a real way of comparing our work to what is possible.

**Comment by amirsagiv83** [comment] 2016-12-08 12:59
@orenafek @michalcohen 
The issue is moved to Michal and will be completed as soon as possible.

**Comment by yossigil** [comment] 2016-12-08 13:07
Well, before that you have to create README.MD, and onvert the project into Maven.
Actually, if README is there this issue is redundant.

**Comment by michalcohen** [comment] 2016-12-09 08:52
Here are some conclusions from "Identifier Highlighter"
* One can create PsiFile via PsiDocumentMenager:
    
![image](https://cloud.githubusercontent.com/assets/11704810/21042884/ed1d750a-bdfc-11e6-8c3c-be9c367ee7a1.png)

* One can find all references to an object via ReferenceSearchL
    
![image](https://cloud.githubusercontent.com/assets/11704810/21042921/214085e8-bdfd-11e6-8b98-49c0c5471395.png)

* This pluging works all the time with "instanceof" instead using visitor because of the reason mentioned in #25 

*  One can fine PsiIdentifier not by using the Psi tree, but by using string matching:
    
![image](https://cloud.githubusercontent.com/assets/11704810/21042988/6e467fc8-bdfd-11e6-9b1c-216ece81ab4b.png)

* One can find the Psi tree upwards:
    
![image](https://cloud.githubusercontent.com/assets/11704810/21043004/7f35b9b6-bdfd-11e6-9c48-01fb6e3b84cf.png)

* One can find initialization on PsiVariable:
   
![image](https://cloud.githubusercontent.com/assets/11704810/21043021/90792e1a-bdfd-11e6-9e3b-dcaa217cdf90.png)

**Comment by yossigil** [comment] 2016-12-09 09:03
Very good job

**Comment by michalcohen** [comment] 2016-12-09 09:41
The plugin "Generate toString" has the coolest utils file named: "PsiAdapter". This file gives a similar behaviour to the auxiliary layer in the Eclipse Spartanizer project. We can get inspired by these methods when expanding the Utils functionality.

for example there are methods such as:
* getPsiElementFactory (really useful when trying to change the source code)
* findClass (return the class in which a PsiElement is in)
* findParentMethod
* isPrimitiveType
* and much more

**Comment by michalcohen** [comment] 2016-12-09 10:04
And @amirsagiv83 here is your credit for the ideas for the plugins: 
![image](https://cloud.githubusercontent.com/assets/11704810/21045110/9be7c9e6-be07-11e6-98f2-4ecc1b115b63.png)
!!!

**Comment by michalcohen** [comment] 2016-12-09 10:07
@yossigil Doesn't this content fit more as an answer for an Issue rather than a Wiki? Isn't a Wiki meant to be used by the user?

**Comment by yossigil** [comment] 2016-12-09 10:40
It is, but we are limited in what we have on github. I think wiki will be less disruptive of progress management. So let's pretend we are the users...

**Comment by amirsagiv83** [comment] 2016-12-09 11:01
Looks great! looks like it's going to be useful for our plugin in some funcionalities

**Closed** 2016-12-11 15:42 UTC
Labels: enhancement
